crate = "axum"
version = "0.8.7"
source = "crates.io"
synced_at_utc = "2026-02-21T11:05:35Z"
history_repo = "lib/vendor-history/axum.git"
history_head = "56e0f2f7278801626dbbc5348efb4fb3d6b9595e"
sync_cmd = "scripts/vendor/inhouse-crate.sh axum 0.8.7"
