crate = "x25519-dalek"
version = "2.0.1"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "c7e468321c81fb07fa7f4c636c3972b9100f0346e5b6a9f2bd0603a52f7ed277"
crate_archive_sha256 = "c7e468321c81fb07fa7f4c636c3972b9100f0346e5b6a9f2bd0603a52f7ed277"
checksum_match = "yes"
upstream_repository = "https://github.com/dalek-cryptography/curve25519-dalek/tree/main/x25519-dalek"
upstream_homepage = "https://github.com/dalek-cryptography/curve25519-dalek"
synced_at_utc = "2026-02-23T09:23:30Z"
history_repo = "lib/vendor-history/x25519-dalek.git"
history_head = "b3c01403757dcebd4c603f0f9c28dc924be49d75"
sync_cmd = "scripts/vendor/inhouse-crate.sh x25519-dalek 2.0.1"
