crate = "serde"
version = "1.0.228"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "9a8e94ea7f378bd32cbbd37198a4a91436180c5bb472411e48b5ec2e2124ae9e"
crate_archive_sha256 = "9a8e94ea7f378bd32cbbd37198a4a91436180c5bb472411e48b5ec2e2124ae9e"
checksum_match = "yes"
upstream_repository = "https://github.com/serde-rs/serde"
upstream_homepage = "https://serde.rs"
synced_at_utc = "2026-02-23T09:32:11Z"
history_repo = "lib/vendor-history/serde.git"
history_head = "eb6297112aad0f87ddbb8223d95617fd6c8c815b"
sync_cmd = "scripts/vendor/inhouse-crate.sh serde 1.0.228"
