crate = "url"
version = "2.5.7"
source = "crates.io"
synced_at_utc = "2026-02-22T18:23:34Z"
history_repo = "lib/vendor-history/url.git"
history_head = "9e33876321d20852542d046979b56be6919caad9"
sync_cmd = "scripts/vendor/inhouse-crate.sh url 2.5.7"
