crate = "ignore"
version = "0.4.25"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "d3d782a365a015e0f5c04902246139249abf769125006fbe7649e2ee88169b4a
d3d782a365a015e0f5c04902246139249abf769125006fbe7649e2ee88169b4a"
crate_archive_sha256 = "d3d782a365a015e0f5c04902246139249abf769125006fbe7649e2ee88169b4a"
checksum_match = "no"
upstream_repository = "https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore"
upstream_homepage = "https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore"
synced_at_utc = "2026-02-23T09:21:50Z"
history_repo = "lib/vendor-history/ignore.git"
history_head = "932118a48f5d111ef261e1e108bbf356269d618f"
materialized_path = "lib/vendor/ignore"
sync_cmd = "scripts/vendor/inhouse-crate.sh ignore 0.4.25"
