crate = "notify"
version = "8.2.0"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "4d3d07927151ff8575b7087f245456e549fea62edf0ec4e565a5ee50c8402bc3"
crate_archive_sha256 = "4d3d07927151ff8575b7087f245456e549fea62edf0ec4e565a5ee50c8402bc3"
checksum_match = "yes"
upstream_repository = "https://github.com/notify-rs/notify.git"
upstream_homepage = "https://github.com/notify-rs/notify"
synced_at_utc = "2026-02-23T09:31:51Z"
history_repo = "lib/vendor-history/notify.git"
history_head = "752b8136c01b100bfc8b8e425f12ef319e97d5d1"
materialized_path = "lib/vendor/notify"
sync_cmd = "scripts/vendor/inhouse-crate.sh notify 8.2.0"
