crate = "regex"
version = "1.12.2"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "843bc0191f75f3e22651ae5f1e72939ab2f72a4bc30fa80a066bd66edefc24d4"
crate_archive_sha256 = "843bc0191f75f3e22651ae5f1e72939ab2f72a4bc30fa80a066bd66edefc24d4"
checksum_match = "yes"
upstream_repository = "https://github.com/rust-lang/regex"
upstream_homepage = "https://github.com/rust-lang/regex"
synced_at_utc = "2026-02-23T09:32:02Z"
history_repo = "lib/vendor-history/regex.git"
history_head = "0a3b531c2397757d758ee3e09da1cfe70c36284c"
materialized_path = "lib/vendor/regex"
sync_cmd = "scripts/vendor/inhouse-crate.sh regex 1.12.2"
