crate = "rusqlite"
version = "0.32.1"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "7753b721174eb8ff87a9a0e799e2d7bc3749323e773db92e0984debb00019d6e
7753b721174eb8ff87a9a0e799e2d7bc3749323e773db92e0984debb00019d6e"
crate_archive_sha256 = "7753b721174eb8ff87a9a0e799e2d7bc3749323e773db92e0984debb00019d6e"
checksum_match = "no"
upstream_repository = "https://github.com/rusqlite/rusqlite"
upstream_homepage = ""
synced_at_utc = "2026-02-23T09:22:16Z"
history_repo = "lib/vendor-history/rusqlite.git"
history_head = "56a38deb796f9bf7ade2ea93f0545d820fc5df23"
materialized_path = "lib/vendor/rusqlite"
sync_cmd = "scripts/vendor/inhouse-crate.sh rusqlite 0.32.1"
