crate = "tokio-stream"
version = "0.1.18"
source = "crates.io"
synced_at_utc = "2026-02-22T18:36:31Z"
history_repo = "lib/vendor-history/tokio-stream.git"
history_head = "94ba626bae40a85be086bcef2b10f297f6e4d3b4"
materialized_path = "lib/vendor/tokio-stream"
sync_cmd = "scripts/vendor/inhouse-crate.sh tokio-stream 0.1.18"
