crate = "tower-http"
version = "0.6.7"
source = "crates.io"
synced_at_utc = "2026-02-22T17:32:56Z"
history_repo = "lib/vendor-history/tower-http.git"
history_head = "e07dc3a68986d50ea109ece58b30a6dc7b79981f"
materialized_path = "lib/vendor/tower-http"
sync_cmd = "scripts/vendor/inhouse-crate.sh tower-http 0.6.7"
