crate = "tower-http"
version = "0.6.8"
source = "crates.io"
synced_at_utc = "2026-02-22T18:25:01Z"
history_repo = "lib/vendor-history/tower-http.git"
history_head = "954fa60bf1e962dc30919a13414833d7efac8e98"
materialized_path = "lib/vendor/tower-http"
sync_cmd = "scripts/vendor/inhouse-crate.sh tower-http 0.6.8"
