[profile]
name = "default"
generated_by = "scripts/vendor/vendor-repo.sh"

[[crate]]
name = "axum"
repo_path = "crates/axum"
manifest_path = "manifests/axum.toml"

[[crate]]
name = "reqwest"
repo_path = "crates/reqwest"
manifest_path = "manifests/reqwest.toml"

[[crate]]
name = "tower-http"
repo_path = "crates/tower-http"
manifest_path = "manifests/tower-http.toml"

[[crate]]
name = "ratatui"
repo_path = "crates/ratatui"
manifest_path = "manifests/ratatui.toml"

[[crate]]
name = "url"
repo_path = "crates/url"
manifest_path = "manifests/url.toml"

[[crate]]
name = "crypto_secretbox"
repo_path = "crates/crypto_secretbox"
manifest_path = "manifests/crypto_secretbox.toml"

[[crate]]
name = "portable-pty"
repo_path = "crates/portable-pty"
manifest_path = "manifests/portable-pty.toml"

[[crate]]
name = "tokio-stream"
repo_path = "crates/tokio-stream"
manifest_path = "manifests/tokio-stream.toml"

[[crate]]
name = "tracing-subscriber"
repo_path = "crates/tracing-subscriber"
manifest_path = "manifests/tracing-subscriber.toml"

[[crate]]
name = "futures"
repo_path = "crates/futures"
manifest_path = "manifests/futures.toml"

[[crate]]
name = "sha1"
repo_path = "crates/sha1"
manifest_path = "manifests/sha1.toml"

[[crate]]
name = "sha2"
repo_path = "crates/sha2"
manifest_path = "manifests/sha2.toml"

[[crate]]
name = "tokio"
repo_path = "crates/tokio"
manifest_path = "manifests/tokio.toml"

[[crate]]
name = "crossterm"
repo_path = "crates/crossterm"
manifest_path = "manifests/crossterm.toml"

[[crate]]
name = "hmac"
repo_path = "crates/hmac"
manifest_path = "manifests/hmac.toml"

[[crate]]
name = "toml"
repo_path = "crates/toml"
manifest_path = "manifests/toml.toml"

[[crate]]
name = "clap"
repo_path = "crates/clap"
manifest_path = "manifests/clap.toml"

[[crate]]
name = "notify-debouncer-mini"
repo_path = "crates/notify-debouncer-mini"
manifest_path = "manifests/notify-debouncer-mini.toml"

[[crate]]
name = "ignore"
repo_path = "crates/ignore"
manifest_path = "manifests/ignore.toml"

[[crate]]
name = "x25519-dalek"
repo_path = "crates/x25519-dalek"
manifest_path = "manifests/x25519-dalek.toml"

[[crate]]
name = "rusqlite"
repo_path = "crates/rusqlite"
manifest_path = "manifests/rusqlite.toml"

[[crate]]
name = "rmp-serde"
repo_path = "crates/rmp-serde"
manifest_path = "manifests/rmp-serde.toml"

[[crate]]
name = "ctrlc"
repo_path = "crates/ctrlc"
manifest_path = "manifests/ctrlc.toml"

