crate = "rmp-serde"
version = "1.3.1"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "72f81bee8c8ef9b577d1681a70ebbc962c232461e397b22c208c43c04b67a155"
crate_archive_sha256 = "72f81bee8c8ef9b577d1681a70ebbc962c232461e397b22c208c43c04b67a155"
checksum_match = "yes"
upstream_repository = "https://github.com/3Hren/msgpack-rust"
upstream_homepage = ""
synced_at_utc = "2026-02-23T09:28:28Z"
history_repo = "lib/vendor-history/rmp-serde.git"
history_head = "0a515b86613c05ab18f14483d8e47fca9a43101d"
sync_cmd = "scripts/vendor/inhouse-crate.sh rmp-serde 1.3.1"
