crate = "crypto_secretbox"
version = "0.1.1"
source = "crates.io"
synced_at_utc = "2026-02-22T18:28:40Z"
history_repo = "lib/vendor-history/crypto_secretbox.git"
history_head = "0a1c004e1f9c97e92b405455a6a31305cda49902"
sync_cmd = "scripts/vendor/inhouse-crate.sh crypto_secretbox 0.1.1"
