crate = "ctrlc"
version = "3.5.1"
source = "crates.io"
registry_index = "https://github.com/rust-lang/crates.io-index"
cargo_registry_checksum = "73736a89c4aff73035ba2ed2e565061954da00d4970fc9ac25dcc85a2a20d790"
crate_archive_sha256 = "73736a89c4aff73035ba2ed2e565061954da00d4970fc9ac25dcc85a2a20d790"
checksum_match = "yes"
upstream_repository = "https://github.com/Detegr/rust-ctrlc.git"
upstream_homepage = "https://github.com/Detegr/rust-ctrlc"
synced_at_utc = "2026-02-23T09:29:16Z"
history_repo = "lib/vendor-history/ctrlc.git"
history_head = "92bd30b481252a2df70de226b81a273b24d10ed8"
sync_cmd = "scripts/vendor/inhouse-crate.sh ctrlc 3.5.1"
